# 一.ndarray
## 1.ndarray的特性
### 多维性
可存在多个维度

In [1]:
import numpy as np

In [7]:
arr=np.array([[1,2,3,4,1],[5,6,7,8,5]])         #创建了一个零维的ndarray的数组
print(arr)
print("arr的维度是",arr.ndim)       #ndim方法返回arr的维度（number of dimensions）

[[1 2 3 4 1]
 [5 6 7 8 5]]
arr的维度是 2


### 同质性
一个ndarray的元素的数据类型是相同的，不同的数据类型会被强转到相同


In [8]:
arr1=np.array([1,2.5])
print(arr1)
arr2=np.array([1,"hello"])
print(arr2)

[1.  2.5]
['1' 'hello']


# 属性


In [4]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(arr)
print("数组的形状",arr.shape)
print("数组的维度数",arr.ndim)
print("数组的元素数",arr.size)
print("数组的元素数据类型",arr.dtype)
print("数组的转置",arr.T)

[[1 2]
 [3 4]]
数组的形状 (2, 2)
数组的维度数 2
数组的元素数 4
数组的元素数据类型 int64
数组的转置 [[1 3]
 [2 4]]


# ndarray的创建

In [5]:
import numpy as np
arr=np.array([[1,2],[3,4]])     #基础构造
list1=[4,5,6]
arr1=np.array(list1,dtype=float)
arr2=np.copy(arr1)

In [6]:
#全0的数组
arr_0=np.zeros((2,3))
#全1的数组
arr_1=np.ones((3,2))
#随机数组
arr_e=np.empty((2,3))
#填充构造
arr_f=np.full((2,3),2)
#相似构造
arr_l=np.ones_like(arr_0)
print(arr_0)
print(arr_1)
print(arr_e)
print(arr_f)
print(arr_l)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [9.45698830e-308 1.89146896e-307 7.56571288e-307]]
[[2 2 2]
 [2 2 2]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#等差数列构造
arr_s=np.arange(1,10,3)
print(arr_s)
arr_m=np.linspace(1,10,5)
print(arr_m)
arr_log=np.logspace(0,4,3,base=2)
print(arr_log)

[1 4 7]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1.  4. 16.]


# 特殊矩阵构造


In [11]:
import numpy as np
#单位矩阵
arr_e=np.eye(3,dtype=int)
print(arr_e)
arr_d=np.diag([1,2,3,0])
print(arr_d)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 0]]


In [5]:
import numpy as np
arr_rand=np.random.randn(3,2)
print(arr_rand,'\n')
arr_uniform1=np.random.uniform(1,0,(3,2))
print(arr_uniform1,"\n")
arr_uniform2=np.random.uniform(0,1,(3,2))
print(arr_uniform2,"\n")
arr_randint=np.random.randint(1,10,(3,2))
print(arr_randint,"\n")
rng=np.random.RandomState(42)
arr_random_state=rng.randint(1,10,(3,2))
print(arr_random_state,"\n")

[[-0.4823419   0.60950712]
 [-0.54899855 -2.6610052 ]
 [-1.8292821  -1.81686961]] 

[[0.51963618 0.17590099]
 [0.03382759 0.09989644]
 [0.04468298 0.24113507]] 

[[0.47038844 0.3913025 ]
 [0.25214048 0.01915071]
 [0.78142263 0.08745133]] 

[[1 6]
 [2 7]
 [6 6]] 

[[7 4]
 [8 5]
 [7 3]] 



# ndarray的数据类型


In [ ]:
import numpy as np
arr_b=np.array([[1,0],[0,1]],dtype=np.bool)
print(arr_b,"\n")
arr_i=np.random.randint(1,10,(3,2),dtype=np.uint8)
print(arr_i,"\n")
arr_ui=np.random.randint(-10,10,(3,2),dtype=np.int8)
print(arr_ui,"\n")


# 索引与切片


In [3]:
#一维数组
import numpy as np
arr=np.random.randint(1,100,10)
print(arr,"\n")
print(arr[9])                   #普通索引
print(arr[2:7])                 #行切片
print(arr[slice(2,7,2)])        #slice函数切片
print(arr[arr>10])          #bool索引

[43 27 52 37  4 37 93 29 89 70] 

70
[52 37  4 37 93]
[52  4 93]
[43 27 52 37 37 93 29 89 70]


In [4]:
#二维数组

In [11]:
arr=np.random.randint(1,100,(4,3))
print(arr,"\n")
print(arr[2,0])     #普通索引
print(arr[1:2,0:1]) #行列切片
print(arr[slice(0,4,2),slice(0,3,2)])
print(arr[1,:][arr[1,:]>10]) #嵌套布尔索引

[[95 77 75]
 [84 93 62]
 [73 36 56]
 [20 58 64]] 

73
[[84]]
[[95 75]
 [73 56]]
[84 93 62]


# ndarray的运算：

In [14]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1+arr2,"\n")
print(arr1-arr2,"\n")
print(arr1*arr2,"\n")
print(arr1+3,'\n')
print(arr1*[1,2],'\n')
print(arr1@arr2,'\n')

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]] 

[[4 5]
 [6 7]] 

[[1 4]
 [3 8]] 

[[19 22]
 [43 50]] 



# 例题

In [2]:
import numpy as np
score=np.array([85,90,78,92,88])
print(np.mean(score),'\n')
print(np.median(score),'\n')
print(np.std(score),'\n')
print(score/1.5)

86.6 

88.0 

4.882622246293481 

[56.66666667 60.         52.         61.33333333 58.66666667]


In [5]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B,"\n")
print(A*B,"\n")
print(A@B,'\n')

[[ 6  8]
 [10 12]] 

[[ 5 12]
 [21 32]] 

[[19 22]
 [43 50]] 



In [11]:
rng=np.random.RandomState(0)
arr=rng.randint(0,10,(3,4))
print(arr,"\n")
print(np.max(arr,axis=0))
print(np.min(arr,axis=1))
print(np.where(arr%2==1,-1,arr))




[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[7 9 7 6]
[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#arr=np.arange(1,13,1)
print(np.reshape(arr,(3,4)))
brr=np.reshape(arr,(3,4))
print(np.mean(brr,axis=1))
print(np.mean(brr,axis=0))
print(arr,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2.5  6.5 10.5]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12] 



In [8]:
arr=np.random.randint(0,20,(5,5))
print(arr,"\n")
print(arr[np.greater(arr,10)])
print(np.where(arr>10,0,arr))

[[ 5  4 17  6 19]
 [ 4  1  8 13  4]
 [16 18 13  9 16]
 [13  1 10 10  1]
 [ 4  3 11 11  2]] 

[17 19 13 16 18 13 16 13 11 11]
[[ 5  4  0  6  0]
 [ 4  1  8  0  4]
 [ 0  0  0  9  0]
 [ 0  1 10 10  1]
 [ 4  3  0  0  2]]


In [9]:
arr=np.array([120,135,110,125,130,140])
print(np.sum(arr),"\n")
print(np.average(arr),"\n")
print(np.var(arr),"\n")
print(np.argmax(arr),"\n")
print(np.argmin(arr),"\n")

760 

126.66666666666667 

97.22222222222223 

5 

2 



In [10]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.concatenate((A,B)))
print(np.reshape(np.concatenate((A,B)),(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
